### ISSUE TITLE
Question - What is the proper format for the project's ExternalID?

### ISSUE THREAD

**Issue by imbeyondboredom** [blackducksoftware/integration-bdio#4]
I would have asked this on the bdio repo but issues are turned off.

In incorporating this library I've found that at times I've scanned projects that have two forges. Ruby Gems and Cocoapods is an example. However the Ruby and Cocoapods "Forges" have different formats. 

In that case, what format should the external ID take? Should it pick one? Is there a standard "Project" format that doesn't rely on the specific forges?

**Comment by ekerwin** [comment]
I'm not sure I understand your question, but I'll do my best.

THIS library, integration-bdio, should allow you to build a SimpleBdioDocument, which would have a single BdioProject and a List of BdioComponents. Each of those BdioComponent objects could come from a different forge and would then have different external ids.

If you are referring to what forge and/or external id to use for the BdioProject, that is really up to you. If you consider it to be a cocoapods project, I'd suggest using that forge, or a rubygems project, use that one, etc. The external id and/or forge of your BdioProject is not hugely important since we aren't trying to match against your project, just its BOM.

Did I get close at all?

**Comment by imbeyondboredom** [comment]
Yep you hit it right on the nose. I thought that was the case but I wasn't sure. Thanks for the clarification!
